# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "base"

  # Define the slave machine

  config.vm.define "slave" do |slave|

  slave.vm.box = "ubuntu/focal64"
  slave.vm.hostname = "slave"
  slave.vm.network "private_network", ip:"192.168.56.104"
  #RUN THE SHELL SCRIPT to set up the LAMP stack
  slave.vm.provision "shell", path: "lamp.sh"

  end
  
  # Define the master machine
  config.vm.define "master" do |master|

  master.vm.box = "ubuntu/focal64"
  master.vm.hostname = "master"
  master.vm.network "private_network", ip:"192.168.56.105"
  #RUN THE SHELL SCRIPT to set up the LAMP stack
  master.vm.provision "shell", path: "lamp.sh"
  
  end

  
end



